Repository googleapis/nodejs-compute, pull requests merged in 2018-05, with the labels that each got.

#71 chore: lock files maintenance
  package-lock.json
  samples/package-lock.json
Labels: cla: yes

#72 Update repo-tools to 2.3.0
  .gitignore
  CONTRIBUTORS
  README.md
  package-lock.json
  package.json
  samples/README.md
  samples/package-lock.json
Labels: cla: yes

#73 Fix Readme.md in /samples
  .cloud-repo-tools.json
  CONTRIBUTORS
  README.md
  package.json
  samples/README.md
  samples/mailjet.js
  samples/package-lock.json
  samples/package.json
  samples/sendgrid.js
  samples/test/.eslintrc.yml
  samples/test/mailjet.test.js
  samples/test/sendgrid.test.js
  samples/vms_api.js
Labels: cla: yes

#74 chore: test on node10
  .circleci/config.yml
Labels: cla: no

#76 Do not show sample for Google API Client library
  .cloud-repo-tools.json
  CONTRIBUTORS
  README.md
  package.json
  samples/README.md
Labels: cla: yes

#77 make samples tests pass
  samples/.eslintrc.yml
  samples/package-lock.json
  samples/package.json
  samples/vms_api.js
Labels: cla: yes

#78 chore: lock files maintenance
  package-lock.json
  samples/package-lock.json
Labels: cla: yes

#80 Add sample demonstrating startup script
  .cloud-repo-tools.json
  README.md
  package.json
  samples/.eslintrc.yml
  samples/README.md
  samples/package-lock.json
  samples/package.json
  samples/startup-script/README.md
  samples/startup-script/apache.png
  samples/startup-script/index.js
  samples/startup-script/package.json
  samples/startup-script/system-test/.eslintrc.yml
  samples/startup-script/system-test/index.test.js
  samples/vms_api.js
Labels: cla: yes

#84 chore: timeout for system test
  package.json
Labels: cla: yes

#86 Increase timeout in startup sample test
  samples/startup-script/package.json
Labels: cla: yes, nightly-failure

#85 Fix problem with multiple deletes in test
  samples/startup-script/index.js
Labels: cla: yes, nightly-failure

#87 chore: the ultimate fix for repo-tools EPERM
  .circleci/config.yml
Labels: cla: yes

#89 chore: run circle as non-root, fix npm link
  .circleci/config.yml
Labels: cla: yes

#88 chore: lock files maintenance
  package-lock.json
  samples/package-lock.json
  samples/package.json
Labels: cla: yes

#91 Simplify JS and use HTML standards mode
  samples/startup-script/index.js
Labels: cla: yes

#92 Update eslint and fix formatting
  package-lock.json
  samples/package-lock.json
  samples/startup-script/index.js
Labels: cla: yes
