Repository googleapis/nodejs-compute, pull requests merged in 2019-06, with the labels that each got.

#323 build: drop dependency on repo tools
  package.json
Labels: cla: yes

#322 feat: support apiEndpoint override
  package.json
  src/index.js
  src/service.js
  src/snapshot.js
  src/vm.js
  test/service.js
  test/snapshot.js
  test/vm.js
Labels: cla: yes

#325 refactor: drop dependency on createErrorClass
  package.json
  src/snapshot.js
  src/vm.js
Labels: cla: yes

#326 feat(docs): move to new googleapis.dev URL
  .repo-metadata.json
  README.md
Labels: cla: yes

#328 build: switch to GitHub magic proxy, for release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#324 chore: release 1.1.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: :rotating_light:, autorelease: pending, cla: yes, type: process

#329 build: fix system tests
  package.json
  system-test/compute.js
Labels: cla: yes, needs work

#333 fix(docs): link to reference docs section on googleapis.dev
  .jsdoc.js
  README.md
Labels: cla: yes

#334 chore: release 1.1.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#335 build: use config file for linkinator
  linkinator.config.json
  package.json
Labels: cla: yes
