Repository googleapis/nodejs-compute, pull requests merged in 2020-06, with the labels that each got.

#444 build: migrate to secret manager
  .kokoro/populate-secrets.sh
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#452 test: cleanup logic causes errors
  samples/test/samples.test.js
  system-test/compute.js
Labels: cla: yes

#451 fix: correct engines range to include node v10
  package.json
Labels: cla: yes

#448 chore(nodejs_templates): add script logging to node_library populate-secrets.sh
  .kokoro/populate-secrets.sh
  .mocharc.js
  synth.metadata
  synth.py
Labels: cla: yes, context: full

#455 build: typo in synth.py breaking autosynth
  synth.py
Labels: automerge, cla: yes

#456 fix: update node issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  synth.metadata
Labels: cla: yes, context: full

#457 build: add config .gitattributes
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full
