Repository googleapis/nodejs-compute, pull requests merged in 2020-09, with the labels that each got.

#492 build: delete Blunderbuss
  .github/blunderbuss.yml
Labels: api: compute, cla: yes

#494 build(test): recursively find test files; fail on unsupported dependency versions
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#497 test: remove prettier dep fixing linting
  package.json
  samples/test/samples.test.js
  src/health-check.js
  src/index.js
  src/region.js
  test/address.js
  test/autoscaler.js
  test/disk.js
  test/firewall.js
  test/health-check.js
  test/image.js
  test/index.js
  test/instance-group-manager.js
  test/instance-group.js
  test/network.js
  test/operation.js
  test/project.js
  test/region.js
  test/rule.js
  test/service.js
  test/snapshot.js
  test/subnetwork.js
  test/vm.js
  test/zone.js
Labels: cla: yes

#500 Implement create instance from instance template
  src/zone.js
  test/zone.js
Labels: api: compute, cla: yes
