Repository googleapis/nodejs-compute, pull requests merged in 2021-01, with the labels that each got.

#530 fix(createVM): do not define machineType or networkInterfaces when template provided
  src/zone.js
  test/zone.js
Labels: api: compute, automerge, cla: yes

#541 fix: handle parameters to image.create()
  src/image.js
  src/index.js
  system-test/compute.js
  test/image.js
Labels: api: compute, cla: yes

#543 refactor(nodejs): move build cop to flakybot
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: compute, automerge, cla: yes, context: full
