Repository googleapis/nodejs-compute, pull requests merged in 2021-05, with the labels that each got.

#551 fix(disks): attach default disk first if needed
  src/zone.js
Labels: api: compute, cla: yes

#553 docs: fixes small typo
  samples/sendgrid.js
  samples/startupScript.js
  samples/test/sendgrid.test.js
  src/index.js
  src/zone.js
Labels: api: compute, cla: yes

#555 [CHANGE ME] Re-generated to pick up changes from synthtool.
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: compute, automerge, cla: yes, context: partial

#557 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: compute, cla: yes, context: full

#554 chore: linting updates
  synth.metadata
Labels: api: compute, automerge, cla: yes, context: none

#562 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  owlbot.py
  synth.metadata
  synth.py
Labels: api: compute, cla: yes
