Repository googleapis/nodejs-compute, pull requests merged in 2022-01, with the labels that each got.

#667 chore: do not run tests on Node 10, use Node 16
  .github/sync-repo-settings.yaml
Labels: automerge, api: compute

#668 fix!: drop support for Node.js 10
  .github/workflows/ci.yaml
  package.json
  samples/package.json
Labels: api: compute

#658 chore(samples): bump version in samples
  samples/package.json
Labels: api: compute, samples

#673 fix: update release_level to reflect current status
  .repo-metadata.json
  README.md
Labels: automerge, api: compute

#671 chore(samples): add create start instance samples
  samples/instances/create-start-instance/createInstanceFromCustomImage.js
  samples/instances/create-start-instance/createInstanceFromPublicImage.js
  samples/instances/create-start-instance/createInstanceFromSnapshot.js
  samples/instances/create-start-instance/createInstanceWithAdditionalDisk.js
  samples/instances/create-start-instance/createInstanceWithSnapshottedDataDisk.js
  samples/instances/create-start-instance/createInstanceWithSubnet.js
  samples/test/createStartInstance.test.js
Labels: api: compute, samples
